#!/usr/bin/env bash

# go sdk
source "${ZSHBOOT_ROOT}/env/go.env.sh" 'go1.24.9'

# go env
export GOPROXY="https://goproxy.cn,direct"
export GOPRIVATE="pkg.deepin.com"

# install goose
command -v goose         >/dev/null 2>&1 || go install github.com/pressly/goose/v3/cmd/goose@latest
command -v golangci-lint >/dev/null 2>&1 || go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.5.0
command -v rclone        >/dev/null 2>&1 || go install github.com/rclone/rclone@v1.71.1
command -v yq            >/dev/null 2>&1 || go install github.com/mikefarah/yq/v4@v4.48.1

# node
source "${ZSHBOOT_ROOT}/env/node.env.sh"    'v20.19.4'

# kubectl
source "${ZSHBOOT_ROOT}/env/kubectl.env.sh" 'v1.23.17'
